const canvas = document.querySelector('#game');
const ctx = canvas.getContext('2d');
const W = canvas.width, H = canvas.height;
const terrain = document.createElement('canvas'); terrain.width=W; terrain.height=H;
const tctx=terrain.getContext('2d');
let terrainPixels;
const state={worms:[],team:0,turn:0,time:20,wind:0.045,projectile:null,particles:[],keys:{},aim:{x:780,y:250},charging:0,held:false,over:false,messageTime:0,last:0};
const colors=['#ed6758','#3cb9b0']; const names=[['Moss','Pip','Rubble'],['Nori','Bloop','Kelp']];

function refreshTerrain(){terrainPixels=tctx.getImageData(0,0,W,H).data}
function terrainShape(){tctx.clearRect(0,0,W,H);tctx.fillStyle='#467e41';tctx.beginPath();tctx.moveTo(0,450);tctx.bezierCurveTo(80,405,150,430,230,390);tctx.bezierCurveTo(315,345,390,400,475,388);tctx.bezierCurveTo(570,370,605,310,700,350);tctx.bezierCurveTo(790,388,860,360,920,400);tctx.bezierCurveTo(1010,440,1100,390,1200,425);tctx.lineTo(W,H);tctx.lineTo(0,H);tctx.closePath();tctx.fill();tctx.fillStyle='#a7c96b';tctx.beginPath();tctx.moveTo(0,450);tctx.bezierCurveTo(80,405,150,430,230,390);tctx.bezierCurveTo(315,345,390,400,475,388);tctx.bezierCurveTo(570,370,605,310,700,350);tctx.bezierCurveTo(790,388,860,360,920,400);tctx.bezierCurveTo(1010,440,1100,390,1200,425);tctx.lineTo(W,445);tctx.bezierCurveTo(1080,410,1020,462,920,420);tctx.bezierCurveTo(850,382,780,410,700,370);tctx.bezierCurveTo(610,330,560,392,475,407);tctx.bezierCurveTo(385,416,315,365,230,410);tctx.bezierCurveTo(150,450,70,425,0,468);tctx.closePath();tctx.fill();refreshTerrain()}
function surfaceY(x){x=Math.max(0,Math.min(W-1,x|0));for(let y=0;y<H;y+=2)if(terrainPixels[(y*W+x)*4+3])return y;return H+10}
function solid(x,y){x|=0;y|=0;return x>=0&&x<W&&y>=0&&y<H&&terrainPixels[(y*W+x)*4+3]>0}
function setup(){terrainShape();state.worms=[];[0,1].forEach(team=>[0,1,2].forEach(i=>{let x=team?790+i*115:170+i*120;state.worms.push({team,name:names[team][i],x,y:surfaceY(x)-18,vx:0,vy:0,hp:100,face:team?1:-1,grounded:true,flash:0})}));Object.assign(state,{team:0,turn:0,time:20,projectile:null,particles:[],charging:0,held:false,over:false,wind:(Math.random()-.5)*.12});show('BRAMBLE BUNCH\'S TURN',1.5);updateHud()}
function active(){return state.worms.filter(w=>w.team===state.team&&w.hp>0)[state.turn%state.worms.filter(w=>w.team===state.team&&w.hp>0).length]}
function updateHud(){let hp=t=>state.worms.filter(w=>w.team===t).reduce((a,w)=>a+Math.max(0,w.hp),0);document.querySelector('#coralHealth').textContent=hp(0)+' HP';document.querySelector('#tealHealth').textContent=hp(1)+' HP';let a=active();document.querySelector('#wormName').textContent=a?.name||'—';document.querySelector('#activeHp').textContent=a?.hp||0;document.querySelector('#round').textContent=String(Math.floor((state.turn+state.team*0)/3)+1).padStart(2,'0');document.querySelector('#turnLabel').textContent=state.over?'MATCH COMPLETE':(state.team?'TIDAL TERRORS':'BRAMBLE BUNCH')+"'S TURN";document.querySelector('#timer').textContent=Math.ceil(state.time);document.querySelector('#timerRing').style.strokeDashoffset=107*(1-state.time/20);document.querySelector('#windArrow').textContent=state.wind>0?'→':'←';document.querySelector('#windPower').textContent=Math.max(1,Math.round(Math.abs(state.wind)*55));document.querySelectorAll('.team-card').forEach((e,i)=>e.classList.toggle('active',i===state.team&&!state.over))}
function show(text,secs=1){let e=document.querySelector('#message');e.textContent=text;e.classList.add('show');state.messageTime=secs}
function move(dt){let w=active();if(!w||state.projectile||state.over)return;let d=(state.keys.ArrowLeft||state.keys.a?-1:0)+(state.keys.ArrowRight||state.keys.d?1:0);if(d){w.vx=d*115;w.face=d}if((state.keys[' ']||state.keys.w||state.keys.ArrowUp)&&w.grounded){w.vy=-320;w.grounded=false;state.keys[' ']=false;state.keys.w=false;state.keys.ArrowUp=false}}
function physics(w,dt){w.vy+=620*dt;w.x+=w.vx*dt;w.y+=w.vy*dt;w.x=Math.max(14,Math.min(W-14,w.x));w.vx*=.82;if(w.vy>=0&&solid(w.x,w.y+18)){while(solid(w.x,w.y+18)&&w.y>0)w.y-=1;w.vy=0;w.grounded=true}else w.grounded=false;if(w.y>H+70&&w.hp>0){w.hp=0;show(w.name+' WENT SWIMMING!',1.3);setTimeout(nextTurn,700)}}
function fire(){let w=active();if(!w||state.projectile||state.over)return;let dx=state.aim.x-w.x,dy=state.aim.y-w.y,mag=Math.hypot(dx,dy)||1,power=250+state.charging*340;state.projectile={x:w.x+w.face*14,y:w.y-8,vx:dx/mag*power,vy:dy/mag*power,life:0};state.charging=0;state.held=false}
function explode(x,y){tctx.save();tctx.globalCompositeOperation='destination-out';tctx.beginPath();tctx.arc(x,y,52,0,Math.PI*2);tctx.fill();tctx.restore();refreshTerrain();for(let i=0;i<44;i++){let a=Math.random()*Math.PI*2,s=60+Math.random()*300;state.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-90,life:.5+Math.random()*.5,color:Math.random()>.5?'#ffc84f':'#ef6a51'})}state.worms.forEach(w=>{let d=Math.hypot(w.x-x,w.y-y);if(d<76&&w.hp>0){let damage=Math.round(78*(1-d/76));w.hp=Math.max(0,w.hp-damage);w.vx+=(w.x-x)/(d||1)*230;w.vy=-Math.abs((w.y-y)/(d||1)*260)-150;w.grounded=false;w.flash=.25;if(w.hp===0)show(w.name+' IS OUT!',1)}});setTimeout(nextTurn,720)}
function nextTurn(){if(state.over)return;let alive=[0,1].map(t=>state.worms.some(w=>w.team===t&&w.hp>0));if(!alive[0]||!alive[1]){state.over=true;show((alive[0]?'BRAMBLE BUNCH':'TIDAL TERRORS')+' WINS!',99);updateHud();return}state.team=1-state.team;state.turn++;state.time=20;state.wind=(Math.random()-.5)*.13;show((state.team?'TIDAL TERRORS':'BRAMBLE BUNCH')+"'S TURN",1);updateHud()}
function drawSky(){ctx.fillStyle='#83d8ed';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff7d7';ctx.beginPath();ctx.arc(105,85,37,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.75;ctx.fillStyle='#fff';[[265,100],[880,80],[1040,180]].forEach(([x,y])=>{ctx.beginPath();ctx.arc(x,y,20,0,7);ctx.arc(x+25,y+5,28,0,7);ctx.arc(x+57,y,18,0,7);ctx.fill()});ctx.globalAlpha=1;ctx.fillStyle='#2f9bbb';ctx.fillRect(0,548,W,72);for(let x=0;x<W;x+=38){ctx.globalAlpha=.3+.2*Math.sin((performance.now()/500)+x);ctx.fillRect(x,556,24,2)}ctx.globalAlpha=1}
function drawTerrain(){ctx.drawImage(terrain,0,0);ctx.globalAlpha=.18;ctx.fillStyle='#254d31';for(let x=20;x<W;x+=53){let y=surfaceY(x);ctx.fillRect(x,y+16,2,H-y)}ctx.globalAlpha=1}
function drawWorm(w){if(w.hp<=0)return;ctx.save();ctx.translate(w.x,w.y);if(w.flash>0)ctx.globalAlpha=.4+Math.sin(performance.now()/20)*.5;ctx.fillStyle=colors[w.team];ctx.strokeStyle='#182843';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(0,2,14,16,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#fff9df';ctx.beginPath();ctx.ellipse(w.face*5,-5,7,7,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#182843';ctx.beginPath();ctx.arc(w.face*7,-5,2,0,7);ctx.fill();ctx.fillStyle='#fff9df';ctx.font='700 12px Baloo 2';ctx.textAlign='center';ctx.strokeStyle='#182843';ctx.lineWidth=3;ctx.strokeText(w.name,0,-29);ctx.fillText(w.name,0,-29);if(w===active()&&!state.projectile&&!state.over){let dx=state.aim.x-w.x,dy=state.aim.y-w.y,a=Math.atan2(dy,dx);ctx.strokeStyle='#182843';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(w.face*5,-6);ctx.lineTo(Math.cos(a)*34,Math.sin(a)*34-6);ctx.stroke();ctx.strokeStyle='#e9d1a0';ctx.lineWidth=3;ctx.stroke();ctx.setLineDash([4,5]);ctx.strokeStyle='#fff9df';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,-8);ctx.lineTo(Math.cos(a)*95,Math.sin(a)*95-8);ctx.stroke();ctx.setLineDash([])}ctx.restore()}
function draw(){drawSky();drawTerrain();state.worms.forEach(drawWorm);if(state.projectile){ctx.fillStyle='#293342';ctx.beginPath();ctx.arc(state.projectile.x,state.projectile.y,6,0,7);ctx.fill();ctx.fillStyle='#ffdd5a';ctx.beginPath();ctx.arc(state.projectile.x-3,state.projectile.y+3,2,0,7);ctx.fill()}state.particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.fillRect(p.x-3,p.y-3,6,6)});ctx.globalAlpha=1;let w=active();if(state.held&&w&&!state.projectile){ctx.fillStyle='#fff8dc';ctx.strokeStyle='#182843';ctx.lineWidth=2;ctx.beginPath();ctx.arc(w.x,w.y-47,13+state.charging*10,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#ed6758';ctx.fillRect(w.x-9,w.y-51,18*state.charging,5)}}
function tick(now){let dt=Math.min(.033,(now-state.last)/1000||0);state.last=now;if(!state.over&&!state.projectile){state.time-=dt;if(state.time<=0){show('TIME UP!',.6);nextTurn()}else move(dt)}if(state.held&&!state.projectile)state.charging=Math.min(1,state.charging+dt*.7);state.worms.forEach(w=>{physics(w,dt);w.flash=Math.max(0,w.flash-dt)});if(state.projectile){let p=state.projectile;p.vx+=state.wind*dt*60;p.vy+=500*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.life+=dt;if(p.x<0||p.x>W||p.y>H||solid(p.x,p.y)||p.life>5){explode(p.x,p.y);state.projectile=null}}state.particles=state.particles.filter(p=>(p.life-=dt)>0&&(p.x+=p.vx*dt,p.y+=p.vy*dt,p.vy+=500*dt,true));if(state.messageTime>0&&(state.messageTime-=dt)<=0)document.querySelector('#message').classList.remove('show');updateHud();draw();requestAnimationFrame(tick)}
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp',' ','Enter'].includes(e.key))e.preventDefault();state.keys[e.key]=true;if(e.key==='r'||e.key==='R')setup();if(e.key==='Enter'&&!state.held&&!state.projectile){state.held=true;state.charging=0}});window.addEventListener('keyup',e=>{state.keys[e.key]=false;if(e.key==='Enter'&&state.held)fire()});canvas.addEventListener('pointermove',e=>{let r=canvas.getBoundingClientRect();state.aim={x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}});canvas.addEventListener('pointerdown',e=>{if(e.button===0&&!state.projectile&&!state.over){state.held=true;state.charging=0}});window.addEventListener('pointerup',()=>{if(state.held)fire()});document.querySelector('#restartTop').onclick=setup;setup();requestAnimationFrame(tick);
